services:
  cloudflared:
    image: symbytech/cloudflare-manager:latest
    container_name: cloudflared
    network_mode: host
#    ports:
#      - "9999:56489"
    build:
      context: .
      dockerfile: ./Dockerfile
      x-bake:
        tags:
          - symbytech/cloudflare-manager:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
#        cache-to: type=registry,ref=symbytech/xbake-demo:cache
    environment:
      - "TZ=Europe/Paris"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: always
    volumes:
      - ./web:/web
