services:
  cloudflared:
    image: symbytech/cloudflare-manager:latest
    container_name: cloudflared
    network_mode: host
    ports:
      - "9152:80"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CLOUDFLARED_VERSION: 2021.8.2
        ARCHS: "amd64 arm64 armv7"
      x-bake:
        tags:
          - symbytech/cloudflare-manager:latest
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
#        cache-to: type=registry,ref=symbytech/xbake-demo:cache
    environment:
      - "TZ=Europe/Paris"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: always
